--- #YAML:1.0
name:               Net-Cassandra-Easy
version:            0.02
abstract:           Easy to use interface to Cassandra
author:
    - Ted Zlatanov <tzz@lifelogs.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:      0
    Class::Accessor:  0
    Moose:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
